---
name: GitHub Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: github-pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build web
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages